#!/bin/sh -e

TARGET=${1:-wheezy}

PACKAGE_VERSION=`dpkg-parsechangelog -l${TARGET}/debian/changelog | grep ^Version: | cut -d\  -f2`
VERSION=`echo $PACKAGE_VERSION | cut -d- -f1 | sed -e s/+dfsg//`
VERSION_MAJOR=`echo $VERSION | cut -d. -f1-2`
TARBALL=mysql-cluster-${VERSION_MAJOR}_${VERSION}+dfsg.orig.tar.gz
TARBALL_SYMLINK=mysql-cluster-${VERSION_MAJOR}_${VERSION}.orig.tar.gz

# Build test options
# nocheck - skip testing (faster build)
# fulltest - very long testsuite
# leave both commented out for the normal test
export DEB_BUILD_OPTIONS=nocheck
#export DEB_BUILD_OPTIONS=fulltest

#add parallel parameter as number of cores +1 in order to make nuild faster 
PROC_CNT=`cat /proc/cpuinfo |grep 'processor\s\+:' | wc -l`
PROC_CNT=$(( $PROC_CNT + 1 ))
export DEB_BUILD_OPTIONS="${DEB_BUILD_OPTIONS} parallel=$PROC_CNT"

# Use ccache if available
if [ `which ccache` ]; then
	export DEB_BUILD_OPTIONS="${DEB_BUILD_OPTIONS} ccache"
fi

# Remove any files from old builds
scripts/clean $TARGET

# Download and extract source
(cd ${TARGET} && debian/rules get-orig-source)
ln -fs ${TARBALL} ${TARBALL_SYMLINK}
tar -C ${TARGET} --strip-components=1 -zxf ${TARBALL_SYMLINK}

# Build package
(cd ${TARGET} && dpkg-buildpackage -uc -us -sa 2>&1 | tee ../build.log)

# Cleanup and done
echo Build complete

