#!/bin/sh -e

DIR=${1:-wheezy}
PACKAGE_VERSION=`dpkg-parsechangelog -l${DIR}/debian/changelog | grep ^Version: | cut -d\  -f2`
VERSION=`echo $PACKAGE_VERSION | cut -d- -f1 | sed -e s/+dfsg//`
VERSION_MAJOR=`echo $VERSION | cut -d. -f1-2`
TARBALL=mysql-cluster-${VERSION_MAJOR}_${VERSION}+dfsg.orig.tar.gz
TARBALL_SYMLINK=mysql-cluster-${VERSION_MAJOR}_${VERSION}.orig.tar.gz

# Build test options
# nocheck - skip testing (faster build)
# fulltest - very long testsuite
# leave both commented out for the normal test
export DEB_BUILD_OPTIONS=nocheck
#export DEB_BUILD_OPTIONS=fulltest

# Use ccache if available
if [ `which ccache` ]; then
	export DEB_BUILD_OPTIONS="${DEB_BUILD_OPTIONS} ccache"
fi

# Remove any files from old builds
scripts/clean

# Download and extract source
(cd ${DIR} && debian/rules get-orig-source)
ln -fs ${TARBALL} ${TARBALL_SYMLINK}
tar -C ${DIR} --strip-components=1 -zxf ${TARBALL_SYMLINK}

# Build package
(cd ${DIR} && dpkg-buildpackage -uc -us -sa 2>&1 | tee ../build.log)

# Cleanup and done
echo Build complete

